algoritmo "Meu Primeiro Programa"
// Este é um programa simples que solicita o nome do usuário e exibe uma mensagem de saudação personalizada.
var
    // Variável para armazenar o nome do usuário
    variavelNome: caractere
inicio
    // Solicita ao usuário que digite seu nome
    escreva("Digite seu nome: ")
        // Lê o nome fornecido pelo usuário e armazena na variável 'variavelNome'
        leia(variavelNome)
    // Escreve uma mensagem de saudação personalizada usando o nome do usuário
    escreva("Olá, ", variavelNome, "!")

fimalgoritmo